### ISSUE TITLE
STROOP not detecting Project64

### ISSUE THREAD

**Issue by Bandu42794** [SM64-TAS-ABC/STROOP#97] opened 2023-06-08 07:53 UTC
I use Project64 as my main emulator, but when I load STROOP on PJ64, there is nothing. Everything is blank. So I have to use mupen64-rerecording (yes I use that).

**Comment by kinderhead** [comment] 2024-01-07 17:11
I don't think PJ64 is supported by STROOP. It's just mupen64-rr and BizHawk

**Comment by danebou** [comment] 2024-04-24 20:56
Yeah its broken right now. Duplicate of #86

**Closed by danebou** 2024-04-24 20:56 UTC
